services:
  - type: web
    name: crisp-backend
    runtime: node
    plan: free
    region: oregon
    branch: main
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: crisp-backend
          property: port
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: CORS_ORIGIN
        value: https://ai-interveiw.netlify.app
      - key: FRONTEND_URL
        value: https://ai-interveiw.netlify.app
